### ISSUE TITLE
[Feature] Add Light Controls

### ISSUE THREAD

**Issue by greghesp** [greghesp/ha-bambulab#11]
Add control and reporting of lighting. 
Currently a WIP in the [lights branch](https://github.com/greghesp/ha-bambulab/tree/lights)

Chamber Light control works, although it is not asynchronous. This leads to the UI "hanging" until it receives an MQTT update to process.  Possibly could make this asynchronous, but not required.

Somehow also need to validate the setup.  Right know it assumes all devices have the Chamber Light, and if its not there, it's marked as unavailable rather than being not being created.
Not sure how to handle this yet, would be better if we could do this before the Platform entities are created

**Comment by AdrianGarside** [comment]
I found that you could add 'available' metadata to the sensors but that didn't remove them from the device, it just present 'Unavailable' in home assistant instead of the sensor value. That was as far as I got.

You can add the chamber light to the P1P - it's part of the early bird gift. I already have so I don't know if there's a difference in report output if it's not present at all.

There is huge dump of all state when the PC app or Handy app connect to the device. I haven't found a way to request that via mqtt yet (I don't even know if it is possible). That only lists the chamber light for me:
    "lights_report": [
      {
        "node": "chamber_light",
        "mode": "off"
      }
    ],
There's a second light that the P1P doesn't have - the toolhead light, which I don't see in any of the data I've been able to dump. Is that the 'work_light' you already had in models.py?

**Comment by AdrianGarside** [comment]
I have figured out how to detect P1P vs X1 from the get_version data. My thinking was to use that to at least mark sensors that the P1P doesn't have as unavailable.

**Comment by AdrianGarside** [comment]
With your X1, if you subscribe to the /request topic - do you see the requests the printer is receiving? I really want to know if there's one generated by the PC/handy app that triggers the huge state dump I see when those connect to the device. I've had no luck capturing network traffic to see if there's an mqtt trigger for that - it seems the PC app doesn't use mqtt at all with the P1P and I have no lan mode option to see if that changes behavior.

**Comment by WolfwithSword** [comment]
If you need the MQTT request that can turn on or off the chamber light, here it is. It does it by name so if the report from the p1p has it as something different, likely renaming the led_node in the command may work.

You know, I never tested to see if these commands work on the flashing work light, but I don't want to try simply because "flashing" is a mode that seems annoying to work with on/off, and also I doubt it would work but don't want to brick anything.

```
on = { "system": { "sequence_id": "2003", "command": "ledctrl", "led_node": "chamber_light", "led_mode": "on", "led_on_time": 500, "led_off_time": 500, "loop_times": 0, "interval_time": 0 }, "user_id": "123456789" }

off = { "system": { "sequence_id": "2003", "command": "ledctrl", "led_node": "chamber_light", "led_mode": "off", "led_on_time": 500, "led_off_time": 500, "loop_times": 0, "interval_time": 0 }, "user_id": "123456789" }
```

**Comment by AdrianGarside** [comment]
That command works the same with the P1P to turn the chamber light on/off. I haven’t messed with the other settings in the payload.

**Comment by WolfwithSword** [comment]
Yeah, no clue what they do or if they have an effect but they were in the original snippet that was pulled.

**Comment by AdrianGarside** [comment]
Waiting with bated for this addition. Being able to turn the chamber light on at the start of a print and off at the end is my top automation desire for my P1P.

**Comment by AdrianGarside** [comment]
If we switch the client back to initializing the device to None:
        self._device: Device | None = None
What happens if HA asks for an async update before we've gotten the mqtt data we need to have that core non-sensor data populated and created it?

We also need to feed the serial through to be the starting 'name' of the device as that ends up being baked into all the HA sensor identities and we need those to be unique to support the multi-printer case.

**Comment by AdrianGarside** [comment]
Here’s the mqtt request payload to get the device to push all state:

{ “pushing”: { “sequence_id”: “1”, “command”: “pushall” }, “user_id”: “1234567890” }

**Comment by AdrianGarside** [comment]
The order of these two needs flipping:

**Comment by AdrianGarside** [comment]
> Valid point, will have to look into the initialisation flow and try to do some stuff there before creating the platforms

I've been trying to learn how to do asynch initialization of the device as that seems to be what we need to do in order to be able to wait for the extra data needed before we tell HA the device is available. I always find the HA docs very lacking for someone starting out.

**Comment by AdrianGarside** [comment]
Yeah, I learn best from examples. Especially when the docs aren't descriptive/complete enough. I was thinking of pulling the core repo too to see how those do things.
