### ISSUE TITLE
[Feature] Expose more triggers

### ISSUE THREAD

**Issue by leonklingele** [greghesp/ha-bambulab#143]
### Describe the feature

For example, I'd like to turn on an LED stripe in different colors based on the "Current Stage" sensor value ("Heatbed Preheating", "Cleaning Nozzle Tip", "Auto Bed Leveling", "Calibrating Extrusion" and "Printing"). Unfortunately, I couldn't find the "Current Stage" trigger in the automation web UI configurator.

Also, I'd be nice to have an "Active Tray", "Current Layer", "Print Status", and more triggers.

<img width="540" alt="Bildschirmfoto 2023-05-15 um 17 29 18" src="https://github.com/greghesp/ha-bambulab/assets/5585491/c27b7ca5-c5e9-4eae-9c6e-dc69e8231688">

### What device is this for?

X1C

**Comment by WolfwithSword** [comment]
If you choose the entity for the stage rather than using a device-based trigger, you can enter in any text for the "from" or "to" values.

It'd be nice to have it be a pre-filled list of trigger values though on the device, and should be possible to add I believe, but using the entity approach would be a good workaround for now if you have the syntax correct.

**Comment by QuinnyPig** [comment]
Yeah, I'd love to, for example, turn on the air scrubber inside the X1C whenever the active tray is loaded with ASA / ABS, or whatnot...

**Comment by WolfwithSword** [comment]
> Yeah, I'd love to, for example, turn on the air scrubber inside the X1C whenever the active tray is loaded with ASA / ABS, or whatnot...

That kind of automation isn't well suited to be, nor designed to be a trigger with HA really, especially since different folks may consider different filaments to be volatile for VOC's (ASA/ABS for sure, but some people consider the same for PETG's and such).

Would be best to have a sensor on the printer that is specifically "the type of filament being printed currently" (thanks to the new virtual tray on X1C to match P1P, it is now possible to get the "current filament/material in use" regardless if it's on an AMS or side-spool), and then build the automation to check if the value is in a list of your VOC filaments.

Something like on the printer a sensor entity of "current material", and it links to the AMS or side-spool to get the tray_type material text from whichever has the in-use flag. Then you can create anything off of this - this is how I currently control my bentobox with my automations too, so I can say it works well 😆

**Comment by AdrianGarside** [comment]
As part of fixing sensor localization the sensors that had text enumeration values got those all listed explicitly. Does this address your feedback?

![image](https://github.com/greghesp/ha-bambulab/assets/26147576/65037108-d980-4f16-bb8a-f4871abc01eb)

**Comment by AdrianGarside** [comment]
Please let us know if the latest changes still have a gap here but I think everything you've listed is now possibly through the web automation UI.
