### ISSUE TITLE
[Feature] Please add camera support (now working on X1C)

### ISSUE THREAD

**Issue by Yoghoo** [greghesp/ha-bambulab#173]
### Describe the feature

Since the last firmware it's possible to view the camera of the X1C in HA.

For instructions see: https://www.wolfwithsword.com/bambulabs-x1c-camera-in-home-assistant/

### What device is this for?

X1C

**Comment by WolfwithSword** [comment]
One thing to note when this gets added (which would have the benefit of having the camera be linked to the device) is that for it to work, the "Lan Liveview" mode has to be turned on via the printer for the X1C, so it should be added as a prerequisite if the user would want to see the camera. LAN Mode is not required.

In order to tell if it is enabled or not, and likely best approach for whether or not the device should setup the camera entity is to watch out for the ipcam messages.

In the `print` payload, if the `ipcam` exists with `rtsp_url` inside, if the value is `disable` then the lan liveview is not enabled. Otherwise, when enabled, it starts with `rtsps` and will actually provide the full url (without authentication or port, both of which not necessary for HA generic camera configuration).

So likely in this case, the flow could be that once the integration receives the ipcam payload, if the rtsp_url is filled with disable, no camera entity exists or mark it as unavailable. Otherwise, it directly gives the URL with correct IP each time, and since the integration already gets the access code, it should be perfect to use and should only be disabled again if the value turns to `disable` or printer goes offline.

Do note that it can be unstable on fresh boot after firmware updates, or sometimes if the printer was booted initially with the setting off. Restarting the printer may fix it. I also have found that sometimes the generic camera integration needs reloading if it is stuck on unavailable for some time - may not be needed for this integration though, would need testing (only encountered it once in the past 2w with manual generic camera).

**Comment by bvrielink** [comment]
> Do note that it can be unstable on fresh boot after firmware updates, or sometimes if the printer was booted initially with the setting off. Restarting the printer may fix it. 

Had this problem as well. Restarting it didn't help (tried a couple of times). I then enabled LAN Mode and directly disabled it again. After another restart it finally worked. Thanks for the article btw. :)

**Comment by tretabyte** [comment]
I'm having the same issue as it everything seems to be turned on, sometimes I can see something for like half a second but then I only see 'Internal Error' or 'connection refused' which is odd, maybe turn it off,on,off, on with a few restarts in between might solve the issue.
since we are talking about cameras, is there a way to pull the print preview that shows the rendered object being printed? it would be great if we could have access to that preview.

**Comment by WolfwithSword** [comment]
> since we are talking about cameras, is there a way to pull the print preview that shows the rendered object being printed? it would be great if we could have access to that preview.

This would only be available after downloading the file from the printer using FTPS, then extracting the correct rendered image. Should be possible in "most" cases, assuming the project/print subtask name is the same (barring extensions) as the 3mf file (then search in the FTPS for the name with known possible extension combinations), then also parsing which plate number is being printed by checking the gcode_file name.

It would definitely be possible, though it has edge cases where it can fail in case stuff was renamed. I'm not sure how the standards are for a HA integration to be downloading files, unzipping them and then extracting, but if it's possible then it likely can be done.

**Comment by AdrianGarside** [comment]
The check looks correct. To test runtime usage you could hard code the answer to False.
