### ISSUE TITLE
[Feature] print_status: cancel

### ISSUE THREAD

**Issue by qwasy** [greghesp/ha-bambulab#176]
### Describe the feature

Can the print_status return a print cancel state?
When I print something on my p1p, and press the stop/cancel button, the print_state doesn't show that. 
If Bambu doesn't have these message, is there another way to return a "print cancel" state?

I've seen issue #44 but that's more for an AMS, which I don't have.

### What device is this for?

P1P

**Comment by AdrianGarside** [comment]
I didn't think that was a state but apparently it is per the report in #191. At least for X1 printers.

**Comment by qwasy** [comment]
Thanks for the update, but it seems it doesn't work with the p1p.
I have LAN Mode enabled, tried it with a cloud print and cancel in Orcaslicer, and another one where I canceled with the screen buttons. Both time no "failed" state was received.

**Comment by AdrianGarside** [comment]
Seems like canceled is distinct from failed then and they don’t consider canceled as failed. Did bambu studio or the handy app say that it was cancelled (and where that wasn’t the source of the cancel request)?

**Comment by AdrianGarside** [comment]
Had some time to send a print and then almost immediately cancel it. Both Bambu Studio and the Handy app popped a print was cancel popup with an error  ('0300 400C 22:55:23' in Bambu Studio, just '225525' (so slightly different value) in the Handy app). Mqtt payload was just the stop command and a 'print_error' value:

{
  "print": {
    "command": "stop",
    "param": "",
    "sequence_id": "22285",
    "reason": "success",
    "result": "success"
  }
}

{
  "print": {
    "nozzle_temper": 75.09375,
    "nozzle_target_temper": 0,
    "bed_temper": 37.34375,
    "bed_target_temper": 0,
    "mc_print_stage": "1",
    "ams_rfid_status": 0,
    **"print_error": 50348044,**
    "wifi_signal": "-57dBm",
    "gcode_state": "IDLE",
    "stg": [],
    "print_type": "idle",
    "mc_print_sub_stage": 0,
    "command": "push_status",
    "msg": 1,
    "sequence_id": "6621"
  }
}

And about 6 seconds later:

{
  "print": {
    "nozzle_temper": 73.875,
    "bed_temper": 38.375,
    **"print_error": 0,**
    "wifi_signal": "-65dBm",
    "command": "push_status",
    "msg": 1,
    "sequence_id": "6623"
  }
}

50348044 = '0x0300400C' in hex. No idea where the 22:55:23 / 225525 value comes from... oh it was the current local time when the 'error' occurred!!!

So it appears that print_error == 0x0300400C is the transient mqtt payload state that indicates a user cancelled print.

**Comment by AdrianGarside** [comment]
Another observation is that a bunch of the values the printer sends don't reset back when you cancel a print (maybe some of them don't when it completes naturally though). The specific one I noticed is the current stage (stg_cur) which is left wherever it was - 'heatbed preheating / 2' in my test even though it definitely cancelled the pre-heat. The associated 'stg' array is however emptied out from:
    "stg": [
      2,
      14,
      13
    ],
    "stg_cur": 2,
to
    "stg": [],
    "stg_cur": 2,

![image](https://github.com/greghesp/ha-bambulab/assets/26147576/92ff6c68-db80-4683-a6de-a1d80367d984)

**Comment by qwasy** [comment]
Nice findings :D
Would it be possible to get the "command": "stop" as an own sensor value?

I only found out, that the print_status goes to idle, when I cancel it. With the not updated value of stg_cur, a bad workaround could be created; like if (idle and current stage != total layer count) -> print canceled
Could work, but it's a bit ugly^^

**Comment by AdrianGarside** [comment]
I’ve been noodling on how we could reasonably expose this transient state and that’s as good as if not better than anything I’ve come up with.

My main concern is I don’t want to mess with prints Bambu actually identifies as in a failed state - but I don’t even know of a way to force that with my P1P. All my print failures result in me canceling the print since the issue is either recoverable (eg replacing a run out spool) or it’s not (eg bad spaghetti).

From a bug introduced by the sensor localization, I now know there is a failed print state in the payload - I’ve just never seen it with my P1P.

**Comment by WolfwithSword** [comment]
To toss in my two cents, I can also say that I've been seeing P1 series users on newer firmwares for the past couple weeks, if they cancel a print, it goes directly to Idle state rather than Failed, which is new behaviour - I have not seen this on X1 series firmware yet but it might be in a beta, since those tend to keep bringing the firmwares of the two closer together.

Previously, any stopped or cancelled print would go to a failed state and persist until a new print came up, whereas a completed print stayed as "Finish". Idle used to be just if it was booted up and hasn't printed yet 😆 

Failed I have yet to see come up on any of these P1 printers anymore actually, since it is hard to get an organic fail of a print since usually it will pause for you to then choose to cancel or proceed. Currently still on X1 series at least. But yeah, unfortunately there is no cancelled state.

As far as I have seen there's only `Idle, Prepare, Running, Pause, Failed, Finish` as potential states. And in recent beta's for P1 series, "Prepare" seems to hang around longer than usual.

While I can't confirm it, what someone could do is verify if when you cancel a print if the subtask name clears or not even if it goes to Idle state. If it is not clear, it's very likely to have been a cancelled print. Since on boot, it will be idle but without a subtask print value. Though not sure if this is viable or if it will hold - no telling if they might do a similar change to "Finish" state either now. If it does work, that can be a simple user-made automation, but shouldn't be relied on for the integration since it is changing provided states.

**Comment by AdrianGarside** [comment]
I'll check but I think the subtask remains unchanged even when a print finishes successfully. Layer count reached seems to be the most effective way to know if a print actually finished or not.

**Comment by WolfwithSword** [comment]
Yeah, subtask stays when it's finish or failed, but wasn't sure about it when it has this new idle behaviour. Would also be interesting to see how any of the other gcode / print sensors behave. Ideally, if one could find a repeatable difference between a) idle from boot, b) print finish, and c) print cancelled and went to idle, then it would be doable to determine if the "idle" is in fact a cancelled print.

Relying on layer count reaching may work but I have a couple of times witnessed a print finish and skip the last layer or two from being reported. Haven't looked for it in ages but it has happened before.

**Comment by AdrianGarside** [comment]
It seems like the best bet is to detect the transient 'printer_error' and raise some kind of event. I'm still trying to wrap my head around how events are supposed to be generated / consumed in home assistant though so I'm not sure how to do it yet or how useful that would actually be in practice.

**Comment by AdrianGarside** [comment]
ChatGPT to the rescue. Seems I need to fire events with a device id in the payload and then I can set up device triggers (https://developers.home-assistant.io/docs/device_automation_trigger/) to allow them to be listed in the UX to easily add automation firing on the events.

**Comment by AdrianGarside** [comment]
https://github.com/greghesp/ha-bambulab/releases/tag/v1.7.0-dev2

Has print failed/canceled and an hms error event. The latter has event data payload you can use in the automation.

**Comment by qwasy** [comment]
Is that a state in print_status?
If so, than it's not working for me...
I tried it twice, once while doing the bed mesh, once in a print.
I've just seen, that you have some trigger stuff in there, I didn't try that.
I'm using NodeRed for all my automations, I need to check, how I can integrate that. But there was a trigger for print canceled.

Also, you should update your manifest.json to 1.7.0, that gave me quite a headache, because it shows 1.6.0 and I updated/rebooted/installed 1.7.0 multiple times while it always showed 1.6.0.

**Comment by qwasy** [comment]
Ahhhh
Okay, yeah I got it working.
For reference, I created a helper variable that gets triggered on the automation. I can read that in NodeRed and do stuff with it.
And nice, it's working :D 
Thank you
