### ISSUE TITLE
[Feature] Remaining % of filament in ams?

### ISSUE THREAD

**Issue by BobFish** [greghesp/ha-bambulab#249]
### Describe the feature

Seeing as the app and studio report this, is it possible to get the amount of filament remaining in each slot of the AMS reported in HA? Haven't seen this if it is already there but doesn't look like it.

Would be very useful for dashboards and automations if possible!

### What device is this for?

AMS

**Comment by AdrianGarside** [comment]
@BobFish I don't have any bambu filaments currently. Can you capture a log file including use of one so I can see what the mqtt payload looks like?

**Comment by AdrianGarside** [comment]
My guess it it'll be this:
          "tray": [
            {
              "id": "0",
              "remain": -1,

But with some value other than -1.  Maybe just gram value estimate?

**Comment by WolfwithSword** [comment]
It'll require both a bambu spool and the filament amount/remaining update setting to be enabled (by default, writing to the remaining amount is not enabled I believe).

If you have the remaining tracking disabled, *all* spools will have a remaining of 0, regardless if Bambu or not.

With it enabled, for spools that don't have the bambu tag, it'll always have the "remain" value of -1, and you can determine if it's a bambu spool or not through various means also found in the "tray" object (tray_uuid won't be all 0's, for ex).

Could probably add it to the tray attributes, but to not be misleading, would need also show if it's one that has remaining-tracking enabled (so any bambu spool - not pulled from the info_idx or profile as some people may use bambu profiles to create custom ones. Can either treat -1 as not supported, or find out via the uuid's.). You'd also want to take care of the case for 0, since that may indicate it's not enabled.

Also - the remaining amount uses how much the spool rotates and the number of metres that go through the feeder back and forth to determine the amount remaining. It then uses this and the known information about filament density and diameter to determine the estimated value for tray_weight. There are no weight-sensors, it's purely calculated.

The actual value will be a percentage from 0-100. For example, I have still an old spool of the pla support that came with the printer over a year ago, came in a 500g amount on a full spool. I've used approximately half of it I'd wager. When I load it up, and in bambustudio enable the calculate remaining option (I've had it disabled since forever since I rarely use bambu filaments, and usually never in the AMS) it shows a value of `23`, and "tray_weight" is 250. 

Images after enabling the setting*

![image](https://github.com/greghesp/ha-bambulab/assets/12175651/b9d1b9f7-a8a4-41a2-9c10-32c9eae6ba43)
![image](https://github.com/greghesp/ha-bambulab/assets/12175651/d112442e-48fe-4957-9ea8-361764d45257)

**Comment by AdrianGarside** [comment]
Thanks Wolf. Very useful.

I see that I have remain = -1 for all my non-bambu spool with the tracking feature disabled (never enabled it). 

So I think it should be:
-1 = Feature not enabled or not a bambu spool
0 = Run out or ???
>0 = Actual % remaining

The only place I'm seeing remain = 0 is for the virtual tray.

Did you have the feature enabled when you were originally using that support filament? Or did it still track usage (but not report it) even with the feature disabled?

**Comment by WolfwithSword** [comment]
Actually come to think of it, I think the bundled support W was 250g so nevermind lol.

I had the feature disabled up until this morning when I tested. So if you've never had it enabled I had 0 for all remains. Now I first enable it, I get -1's.

I think back now, I've prob used maybe 50g at most of the support W, so turning on the feature so an old, used spool tracks it as if it is new/full (and those tags were preset at 250g I believe).

**Comment by AdrianGarside** [comment]
It's odd that you were seeing 0 for all the remains and I am seeing -1 seemingly for the same state (never enabled the tracking). Maybe the P1 and X1 machines are inconsistent in that behavior. Alternatively, I turned the feature on at some point in the distance past and then off again and that permanently results in -1 values instead of 0.

**Comment by BobFish** [comment]
I notice also the values shown in bambu studio seem a little inconsistent (it'll fluctuate between being accurate and a bit higher or lower before fixing itself every now and then), still it does seem like it could be useful as long as its mostly accurate.

Thanks @WolfwithSword for the info. If there's anything I can help with still let me know. (How / where do I access these logs?)

**Comment by AdrianGarside** [comment]
You can get a full dump of everything the printer sends with:
![image](https://github.com/greghesp/ha-bambulab/assets/26147576/09b8661c-d6b9-4714-bffa-63236cccb74c)
and then:
![image](https://github.com/greghesp/ha-bambulab/assets/26147576/8e8a8a79-d862-43c9-bda6-8eed12273a61)

**Comment by myMartek** [comment]
I added a pull request which simply adds the remain value as it is to each AMS Slot. It can be -1 if there is no bambu filament or when the option to track the state is disabled but for me it is still a valid reading we can show as it is.

<img width="575" alt="Bildschirmfoto 2023-11-24 um 22 28 08" src="https://github.com/greghesp/ha-bambulab/assets/3337806/1ab9bfa3-5f17-4419-8534-0bf50ed5485a">

**Comment by myMartek** [comment]
I also added the tag_uid value which is 000000000 on non bambulab filament.

My idea is: I want to create a simple Web-Frontend that will keep track of all filaments you have put into the AMS. I am one of those guys who mostly use Bambus filaments and with the remain + tag_uid I can keep track of all filaments that went to the AMS including type (pla basic, pla matte, etc.), remain value and color.

Having those information will allow me to automatically keep a list of all filaments I have in my house and how much filament is left. If you want I will share a github link when I have finished the portal in some weeks.

<img width="569" alt="Bildschirmfoto 2023-11-24 um 22 40 15" src="https://github.com/greghesp/ha-bambulab/assets/3337806/3a317f64-1cb7-4b1d-8608-5d3970460ec7">
