### ISSUE TITLE
[Bug] 'list changed size during iteration' exception

### ISSUE THREAD

**Issue by jfroy** [greghesp/ha-bambulab#256]
### Describe the bug

I see this error in the logs:

```
This error originated from a custom integration.

Logger: custom_components.bambu_lab.pybambu
Source: custom_components/bambu_lab/pybambu/bambu_client.py:203
Integration: Bambu Lab (documentation, issues)
First occurred: 08:36:56 (1 occurrences)
Last logged: 08:36:56

Exception args: ('list changed size during iteration',)
```

[config_entry-bambu_lab-2c24dcf3708c40d11d2b9993b5d607ea.json.txt](https://github.com/greghesp/ha-bambulab/files/13044979/config_entry-bambu_lab-2c24dcf3708c40d11d2b9993b5d607ea.json.txt)

### To Reproduce

I don't know.

### Expected Behaviour

No exception.

### What device are you using?

X1C

### Diagnostic Output

```shell
I can't seem to be able to attach the file in this field.
```

**Comment by jfroy** [comment]
Looking at the code, this isn't going to be enough to identify the issue. I'll enable debug logging to have the messages in the logs.

**Comment by AdrianGarside** [comment]
Yep, unfortunately we likely need more context to narrow down where that's coming from. I'll take a look through the code and see if I can work it out by inspection.

**Comment by AdrianGarside** [comment]
The exception is being thrown from coordinator.py:
`
    def _update_data(self):
        device = self.get_model()
        self.async_set_updated_data(device)
`

Previously added locking caused the exception to then permanently hang the mqtt thread causing the integration to show stale data. I've removed the locking since it was a failed fix attempt for a different issue I ultimately fixed a different way so I don't believe it's necessary. 

The self.get_model() call looks innocuous. I don't see how anything it does could throw the 'list changed size during iteration' exception. So that leaves the async_set_update_data() call which is unfortunately a call into home assistant. So HA must be then querying the device for all the provided sensor data while new data comes in. Which because that call is async is definitely possible.
