### ISSUE TITLE
[Feature] Display end time without date

### ISSUE THREAD

**Issue by user858753257** [greghesp/ha-bambulab#338]
Maybe via an option

**Comment by AdrianGarside** [comment]
What if we simply cull the date when it's today?

**Comment by AdrianGarside** [comment]
https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.3-dev1

**Comment by user858753257** [comment]
> What if we simply cull the date when it's today?

That's a good idea 👍

**Comment by user858753257** [comment]
That was a fast implementation. Thanks for that 😁

**Comment by AdrianGarside** [comment]
@user858753257 this change got reversed as it makes the sensor value very difficult to use from automation. Instead the sensor values are now datetime objects. It's still possible for you to get the result you want with a template sensor. This will look something like this (but definitely not exactly this since this was written for the old string form of the sensor value) where now you can operate directly on the datetime instead of first having to convert it to one.
- sensor:
    - name: Bambu X1C Printer Job ETA
      state: |
        {% set sensor_datetime = strptime(states('sensor.bambu_x1c_printer_end_time'), '%d %B %Y %H:%M:%S') %}
        {% set current_datetime = now().replace(hour=0, minute=0, second=0, microsecond=0) %}
        {% if sensor_datetime.date() == current_datetime.date() %}
          {{ sensor_datetime | as_timestamp | timestamp_custom('%I:%M %p', true) }}
        {% else %}
          {{ sensor_datetime | as_timestamp | timestamp_custom('%m/%d/%Y %I:%M %p', true) }}
        {% endif %}
      icon: mdi:clock

    - name: Bambu X1C Printer Job Remaining
      state: |
        {{ strptime(states('sensor.bambu_x1c_printer_end_time'), '%d %B %Y %H:%M:%S')  | as_local }}
      device_class: timestamp      
      icon: mdi:timer
