### ISSUE TITLE
[Feature] AMS humidity

### ISSUE THREAD

**Issue by kurim** [greghesp/ha-bambulab#486]
### Describe the feature

Update AMS humidity to match Bambulab App info.

Current state:
![image](https://github.com/greghesp/ha-bambulab/assets/1880220/2cf2a48d-2719-4740-aa96-92aacc092b43)

App state:
![IMG_7679](https://github.com/greghesp/ha-bambulab/assets/1880220/0ebb39b6-cbbd-461a-a3b1-1ccde633c382)

1 - dry / 5 - wet

### What device is this for?

AMS

**Comment by AdrianGarside** [comment]
I’m not sure what you’re asking for? The humidity index value is already reported and is the same number as shown in the Bambu handy app. It probably shouldn’t be reported as a percentage measurement type since it isn’t. But they integration doesn’t currently have any prebuilt in Lovelace UI but you could build your own.

**Comment by AdrianGarside** [comment]
Ah, I see. I hadn't realized Bambu had inverted the values recently in their apps.
