### ISSUE TITLE
[Bug] Printer status switches to offline randomly

### ISSUE THREAD

**Issue by SoCuul** [greghesp/ha-bambulab#493]
### Describe the bug

When my printer is idle, its status randomly switches sometimes to offline, then reverts back to idle a few seconds later.

### To Reproduce

1. Set up an automation to log each time the status changes/check history

*Note: I have not been able to reproduce this consistently, but this is how I have known that it goes offline.

### Expected Behaviour

Status should stay idle consistently.

### What device are you using?

A1

### Diagnostic Output

```shell
https://pastebin.com/raw/7BEs2qk4
```

**Comment by AdrianGarside** [comment]
This is the watchdog timer firing - which happens if the printer doesn't send data for a long enough time (30 seconds). It triggers a call from the integration to the printer to turn data back on as there is (was?) some kind of idle out going on where it would silently stop sending data unless told to keep doing so. The watchdog time also handles the case when the printer truly did go offline so that we can detect it correctly even in cloud mode where we never actually know it went offline since the cloud mqtt connection never drops.
