### ISSUE TITLE
[Feature] Don't translate entity IDs

### ISSUE THREAD

**Issue by scurfin** [greghesp/ha-bambulab#773]
### Describe the feature

It would make sense if the entity IDs were not translated. I use Home Assistant in German and therefore all entity IDs have been translated into German. 
However, it is extremely time-consuming to use the Bambulab dashboard https://www.wolfwithsword.com/bambulab-home-assistant-dashboard/, for example, because all the YAMLs generated have to be edited manually in such a time-consuming way

### What device is this for?

P1S

**Comment by AdrianGarside** [comment]
Entities should be translated to the configured language for the home assistant instance.

**Comment by TheMicroDevil** [comment]
> Entities should be translated to the configured language for the home assistant instance.

My home assistant language is English, but the entities are  still translated to German.
I also think it would make sense to leave the decision to the user instead of translating something half-heartedly, which leads to completely breaking my dashboard after every update (600 lines of code) because someone had a new idea for renaming the entities again ;)
![Auswahl_012](https://github.com/user-attachments/assets/682b4275-4159-4533-90dd-b0454d38ac6a)

**Comment by eMerzh** [comment]
Hey, chimming in, i must say that i agree here, i was surprise to see the entities beeing translated 🤔 
i mean, description & stuff must be translated, but not the ids ... also it leads to the dashboard generator not doing anything 🤔  i had to find corresponding items 1 by 1
