### ISSUE TITLE
[Feature] Google Oath Login

### ISSUE THREAD

**Issue by mike391** [greghesp/ha-bambulab#83]
### Describe the feature

Is it possible to use cloud mqtt with Google Oath Login?

### What device is this for?

P1P

**Comment by AdrianGarside** [comment]
Is this different to the existing cloud mqtt support that just got added? I don't recall the options when I set up my printer but if google was offered as I choice I would immediately have ignored that as google doesn't need my help to record everything about me.

**Comment by mike391** [comment]
Yea, when you login on Bambu labs website, they have a user and password field. But at the bottom of the login window there are icons to login with Google, Facebook or Apple id. 

In the meantime, Is their a way to manually extract the login token from the browser and manually add it to a config file in home assistant?

**Comment by AdrianGarside** [comment]
That's great to know. Reopening this to track documenting that approach in the README.

**Comment by darrenoc3** [comment]
The README doesn't explain this option at all, it still talks about using a google account app password (which didn't work for me)

**Comment by AdrianGarside** [comment]
Someone with a google account needs to provide me explanatory text since I'm not registered with a google account.

**Comment by darrenoc3** [comment]
@AdrianGarside 
If you signed up using any OAuth method, you need to set a password for your Bambu Cloud account:
1. Login to the Bambu mobile app using OAuth.
2. Tap the person icon at the bottom right.
3. Tap Account Security > Change Password
This will allow you to set a password. Now you can login to the HA integration using your Bambu username and password instead of OAuth.

**Comment by AdrianGarside** [comment]
Awesome. I'll use those instructions verbatim then.
